source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JSZVCR_Example', :exclusive => true do
  pod "JSZVCR", :path => "../"
end

target 'JSZVCR_Tests', :exclusive => true do
  pod "JSZVCR", :path => "../"

  
end
